# Default values for superdentist-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/superdentist/superdentist-frontend
  tag: latest
  port: 8080
  pullPolicy: Always

sdServiceAccount:
  name: superdentist-backend
  secret: superdentist-backend
  credential:
    dir: /var/run/secrets/superdentist-backend
    file: super-dentist-backend.json
sdAPISecret:
  name: sd-api-key
  secret: GCP_API_KEY

service:
  type: ClusterIP
  port: 80